# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 10:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20160518_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitter',
            name='species_of_animal_can_take',
        ),
    ]
