# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_sitter_species_of_animal_can_take'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitter',
            name='gender',
            field=models.CharField(max_length=10),
        ),
    ]
