# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20160518_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitter',
            name='phoneNumber',
            field=models.CharField(max_length=12),
        ),
    ]
