# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_sitter_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitter',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
