# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20160522_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitter',
            name='address',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='sitter',
            name='dwelling',
            field=models.CharField(max_length=100),
        ),
    ]
