# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 14:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateField(default=datetime.datetime(2016, 5, 12, 14, 29, 57, 246688, tzinfo=utc)),
        ),
    ]
