# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 12:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0003_auto_20160517_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateField(default=datetime.datetime(2016, 5, 17, 12, 49, 47, 298772, tzinfo=utc)),
        ),
    ]
