# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0005_auto_20160517_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='daily_payment',
            field=models.IntegerField(default=10000),
        ),
    ]
