# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_auto_20160517_2345'),
        ('posting', '0006_post_daily_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='species_of_animal',
            field=models.ManyToManyField(to='contact.Species'),
        ),
    ]
