# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 14:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 12, 14, 29, 57, 249749, tzinfo=utc)),
        ),
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together=set([('user', 'post')]),
        ),
    ]
