# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 12:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20160517_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='published_date',
            field=models.DateField(default=datetime.datetime(2016, 5, 17, 12, 49, 47, 307906, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='contact',
            name='species_of_animal',
            field=models.ManyToManyField(to='contact.Species'),
        ),
        migrations.AlterField(
            model_name='review',
            name='published_date',
            field=models.DateField(default=datetime.datetime(2016, 5, 17, 12, 49, 47, 309692, tzinfo=utc)),
        ),
    ]
