# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_remove_review_sitter'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='status',
            field=models.CharField(default='wait', max_length=30),
        ),
    ]
