# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_contact_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='name',
            field=models.CharField(choices=[('개/강아지', '개/강아지'), ('고양이', '고양이'), ('토끼', '토끼'), ('소동물', '소동물'), ('파충류', '파충류')], max_length=10),
        ),
    ]
