# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_auto_20160524_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='contact',
            name='start_date',
            field=models.DateField(),
        ),
    ]
