# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_auto_20160518_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='photo',
            field=models.ImageField(default='/media/petgalary/default_profile.png', upload_to='petgalary'),
        ),
    ]
